### ISSUE TITLE
Faut-il mettre à jour la commande de test dans la documentation du squelette?

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/S20203-LOG210-Lab0#20]
https://github.com/profcfuhrmanets/S20203-LOG210-Lab0/blob/maj-squelette-ete2/docs/Squelette.md

indique encore `npm run test` comme commande pour exécuter les tests.

**Comment by Olon11** [comment]
Même chose pour l'étape :

```
- [ ] vérifier que les tests passent (Node.js)

npm test devrait indiquer que tous les tests passent.
```

**Comment by Olon11** [comment]
Même chose pour l'étape Vérifier la correction automatique :

```
Assurez-vous qu'aucun test n'est en échec et que la couverture de test est de 100%.

npm test
```

**Comment by fuhrmanator** [comment]
Je crois que la chose la plus simple est de changer `npm test` à la commande qui lance les tests seulement pour le lab0.
