### ISSUE TITLE
Points pour la couverture de test

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/S20203-LOG210-Lab0#24]
Ajouter des points pour la couverture de test de 100% dans le bareme de correction du fichier readme.md

**Comment by fuhrmanator** [comment]
Combien? Il faut que ça vaille la peine si on veut que les étudiants le fassent. 20%?

**Comment by RubenLaden** [comment]
Une astuce pour ajouter des exigences sans avoir à trop retoucher au barème est d'ajouter des points négatifs. Par exemple :
Couverture == 100% : 0 points
Couverture >= 90%: -3 points
Couverture >= 80%: -6 points
Couverture < 80%: -10 points

**Comment by fuhrmanator** [comment]
Puisqu'on ne sait pas a priori combien de couverture est déjà possible avec les tests en place, je préfere une grille qui donne tout ou rien. Ceci sera pour la prochaine fois:

## Calcul de la note

Le calcul de la note du laboratoire se fait à partir des résultats des tests automatiques et une évaluation faite par l'auxiliaire d'enseignement:

| variable | explication |
|:-:|:-|
| *e* | 10 points si vous avez complété un texte d'au moins 300 mots dans `docs/experience-parasites-mollassons.md` (sinon 0 point)|
|*b*<sup>*</sup>| nombre de nouveaux boutons fonctionnels (max 3)|
| *c*<sup>*</sup>| 10 points si la page de classement fonctionne correctement (sinon 0 point) |
| *C*<sup>*</sup>| 10 points si la couverture des tests est 100 % (sinon 0 point) |
| *v* | nombre de tests valides ("passed")|
| *d* | nombre de tests déjà valides au début du projet (actuellement 2)|
| *t* | nombre total de tests |


<sup>*</sup>évaluation faite par l'auxiliaire d'enseignement

<img src="https://latex.codecogs.com/png.latex?%5Cdpi%7B300%7D%20%5Cbg_white%20%5Ctextrm%7BNote%20finale%7D%20%3D%20%5Cfrac%7Be%20&plus;%202b%20&plus;%20c%20&plus;%20C%20&plus;%20v%20-%20d%7D%7B10%20&plus;%206%20&plus;%2010%20&plus;%2010%20&plus;%20t%20-d%7D%20100" width="400">

SVP me donner votre feedback ici (ça concerne également #25). 

Quant à la correction manuelle de la GUI (b, c), il y a théoriquement un moyen de faire des tests automatiques, mais je trouve que ça sort du cadre du cours et risque d'ajouter des nouvelles bibliothèques au squelette/lab0. Pour la couverture C, je pense que c'est possible de l'extraire par un script (@yvanross le saura probablement).
