### ISSUE TITLE
Mettre à jour le dépôt pour qu'il soit synchronisé avec les changements dans le squelette

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/S20203-LOG210-Lab0#5]

**Comment by fuhrmanator** [comment]
Il est important de documenter comment le faire. @Olon11 as-tu une idée?

**Comment by Olon11** [comment]
Ce dépôt est lié au template du squelette. Il y a une commande git qui permet de synchroniser les changements. Par la suite, il faut juste remplacer l'énoncé par celui du laboratoire 0. 

https://stackoverflow.com/a/56577320
